from __future__ import annotations

import smtplib
from email.message import EmailMessage
from typing import Final

from aiosmtplib import SMTP


class _ProtonEmailBase:
    _SMTP_SERVER: Final = "smtp.protonmail.ch"
    _SMTP_PORT: Final = 587

    def __init__(
        self,
        email_address: str,
        smtp_token: str,
    ) -> None:
        self.email_address = email_address
        self.smtp_token = smtp_token


class AsyncProtonEmailClient(_ProtonEmailBase):
    """Async client for sending proton emails.

    For setup instructions see https://proton.me/support/smtp-submission

    Args:
        email_address: The email address used when setting up the Proton SMTP token
        smtp_token: The token generated by Proton when setting up SMTP
    """

    def __init__(
        self,
        email_address: str,
        smtp_token: str,
    ) -> None:
        super().__init__(email_address=email_address, smtp_token=smtp_token)

    async def send_email(
        self,
        *,
        message: str,
        email_to: str,
        subject: str,
        html_content: str | None = None,
    ) -> None:
        """Send the email through Proton.

        Args:
            message: The message body. If not html_content is provided or the receiving client does
                not support HTML this is used.
            email_to: The email address where the email should be sent
            subject: The subject of the email
            html_content: The message body with HTML markup. Defaults to None

        Examples:
            >>> from message_sender.email.proton import AsyncProtonEmailClient
            >>>
            >>> client = AsyncProtonEmailClient(
            >>>     email_address="smtp_setup_email@proton.me", smtp_token="your-token"
            >>> )
            >>> await client.send_email(
            >>>     message="Your message body",
            >>>     email_to="someone@email.com",
            >>>     subject="Example",
            >>>     html_content="<p>Your HTML message body</p>",
            >>> )
        """

        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = self.email_address
        msg["To"] = email_to
        msg.set_content(message)

        if html_content:
            msg.add_alternative(html_content, subtype="html")

        async with SMTP(
            hostname=self._SMTP_SERVER,
            port=self._SMTP_PORT,
            username=self.email_address,
            password=self.smtp_token,
            start_tls=True,
        ) as smtp:
            await smtp.send_message(msg)


class ProtonEmailClient(_ProtonEmailBase):
    """Client for sending proton emails.

    For setup instructions see https://proton.me/support/smtp-submission

    Args:
        email_address: The email address used when setting up the Proton SMTP token
        smtp_token: The token generated by Proton when setting up SMTP
    """

    def __init__(
        self,
        email_address: str,
        smtp_token: str,
    ) -> None:
        super().__init__(email_address=email_address, smtp_token=smtp_token)

    def send_email(
        self,
        *,
        message: str,
        email_to: str,
        subject: str,
        html_content: str | None = None,
    ) -> None:
        """Send the email through Proton.

        Args:
            message: The message body. If not html_content is provided or the receiving client does
                not support HTML this is used.
            email_to: The email address where the email should be sent
            subject: The subject of the email
            html_content: The message body with HTML markup. Defaults to None

        Examples:
            >>> from message_sender.email.proton import ProtonEmailClient
            >>>
            >>> client = ProtonEmailClient(
            >>>     email_address="smtp_setup_email@proton.me", smtp_token="your-token"
            >>> )
            >>> client.send_email(
            >>>     message="Your message body",
            >>>     email_to="someone@email.com",
            >>>     subject="Example",
            >>>     html_content="<p>Your HTML message body</p>",
            >>> )
        """

        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = self.email_address
        msg["To"] = email_to
        msg.set_content(message)

        if html_content:
            msg.add_alternative(html_content, subtype="html")

        with smtplib.SMTP(self._SMTP_SERVER, self._SMTP_PORT) as smtp:
            smtp.starttls()
            smtp.login(self.email_address, self.smtp_token)
            smtp.send_message(msg)
